CREATE TABLE IF NOT EXISTS roles (
  id_role SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(50) NOT NULL UNIQUE,
  descricao VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS usuarios (
  id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  senha VARCHAR(255),
  hash_senha VARCHAR(255),
  nivel_acesso VARCHAR(20) NOT NULL DEFAULT 'user' CHECK (nivel_acesso IN ('master', 'admin', 'user')),
  ativo SMALLINT NOT NULL DEFAULT 1,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS usuarios_roles (
  id_usuario BIGINT NOT NULL REFERENCES usuarios(id_usuario),
  id_role SMALLINT NOT NULL REFERENCES roles(id_role),
  PRIMARY KEY (id_usuario, id_role)
);

CREATE TABLE IF NOT EXISTS password_resets (
  id_reset BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario BIGINT REFERENCES usuarios(id_usuario),
  user_id BIGINT REFERENCES usuarios(id_usuario),
  token_hash VARCHAR(255) NOT NULL UNIQUE,
  expires_at TIMESTAMP NOT NULL,
  used_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ativo SMALLINT NOT NULL DEFAULT 1
);

CREATE INDEX IF NOT EXISTS idx_password_resets_usuario ON password_resets(id_usuario);
CREATE INDEX IF NOT EXISTS idx_password_resets_user ON password_resets(user_id);
CREATE INDEX IF NOT EXISTS idx_password_resets_expiracao ON password_resets(expires_at);

CREATE TABLE IF NOT EXISTS fornecedores (
  id_fornecedor BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cnpj VARCHAR(18) UNIQUE,
  nome VARCHAR(255),
  nome_fornecedor VARCHAR(255),
  email VARCHAR(255),
  telefone VARCHAR(20),
  contato VARCHAR(255),
  inscricao_estadual VARCHAR(50),
  observacoes TEXT,
  criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS categorias (
  id_categoria INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(255),
  nome_categoria VARCHAR(255),
  descricao TEXT
);

CREATE TABLE IF NOT EXISTS setores_locais (
  id_setor_local INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(255),
  nome_setor_local VARCHAR(255),
  localizacao VARCHAR(255),
  descricao TEXT,
  responsavel VARCHAR(255),
  capacidade INTEGER,
  andar VARCHAR(50),
  ativo SMALLINT NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS centro_custo (
  id_centro_custo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(50),
  nome VARCHAR(255),
  nome_centro VARCHAR(255),
  descricao TEXT,
  ativo SMALLINT NOT NULL DEFAULT 1,
  notas TEXT
);

CREATE TABLE IF NOT EXISTS status_patrimonio (
  id_status_patrimonio SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(50) NOT NULL UNIQUE,
  descricao VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS tipos_movimentacao (
  id_tipo_movimentacao SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(50) NOT NULL UNIQUE,
  descricao VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS status_manutencao (
  id_status_manutencao SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(50) NOT NULL UNIQUE,
  descricao VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS tipos_manutencao (
  id_tipo_manutencao SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(50) NOT NULL UNIQUE,
  descricao VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS notas_fiscais (
  id_nota_fiscal BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero_nota VARCHAR(255) NOT NULL UNIQUE,
  data_emissao DATE NOT NULL,
  valor_total NUMERIC(12,2) NOT NULL,
  id_fornecedor BIGINT REFERENCES fornecedores(id_fornecedor),
  id_centro_custo INTEGER REFERENCES centro_custo(id_centro_custo),
  caminho_arquivo VARCHAR(255),
  caminho_arquivo_nf VARCHAR(255)
);

CREATE INDEX IF NOT EXISTS idx_notas_fiscais_data_emissao ON notas_fiscais(data_emissao);

CREATE TABLE IF NOT EXISTS itens_nota_fiscal (
  id_item_nf BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_nota_fiscal BIGINT REFERENCES notas_fiscais(id_nota_fiscal),
  id_patrimonio BIGINT,
  descricao VARCHAR(255),
  quantidade INTEGER NOT NULL DEFAULT 1 CHECK (quantidade > 0),
  valor_unitario NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (valor_unitario >= 0),
  ncm VARCHAR(20),
  cfop VARCHAR(20)
);

CREATE INDEX IF NOT EXISTS idx_nfi_nota ON itens_nota_fiscal(id_nota_fiscal);

CREATE TABLE IF NOT EXISTS patrimonios (
  id_patrimonio BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero_patrimonio BIGINT UNIQUE,
  nome VARCHAR(255) NOT NULL,
  descricao TEXT,
  numero_serie VARCHAR(255) UNIQUE,
  valor_compra NUMERIC(12,2) CHECK (valor_compra IS NULL OR valor_compra >= 0),
  valor_atual NUMERIC(12,2) CHECK (valor_atual IS NULL OR valor_atual >= 0),
  quantidade INTEGER NOT NULL DEFAULT 1,
  numero_nota VARCHAR(50),
  data_aquisicao DATE,
  estado_conservacao VARCHAR(20) CHECK (estado_conservacao IS NULL OR estado_conservacao IN ('novo', 'bom', 'regular', 'ruim')),
  status VARCHAR(20) NOT NULL DEFAULT 'ativo' CHECK (status IN ('ativo', 'baixado', 'em_manutencao', 'desaparecido')),
  id_categoria INTEGER REFERENCES categorias(id_categoria),
  id_fornecedor BIGINT REFERENCES fornecedores(id_fornecedor),
  id_setor_local INTEGER REFERENCES setores_locais(id_setor_local),
  id_item_nf BIGINT REFERENCES itens_nota_fiscal(id_item_nf),
  id_status_patrimonio SMALLINT REFERENCES status_patrimonio(id_status_patrimonio) DEFAULT 1,
  data_cadastro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_patrimonios_categoria ON patrimonios(id_categoria);

CREATE TABLE IF NOT EXISTS patrimonios_centro_custo (
  id_patrimonio BIGINT NOT NULL REFERENCES patrimonios(id_patrimonio),
  id_centro_custo INTEGER NOT NULL REFERENCES centro_custo(id_centro_custo),
  inicio_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  fim_em TIMESTAMP,
  PRIMARY KEY (id_patrimonio, id_centro_custo, inicio_em),
  CHECK (fim_em IS NULL OR fim_em >= inicio_em)
);

CREATE TABLE IF NOT EXISTS movimentacoes (
  id_movimentacao BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_patrimonio BIGINT REFERENCES patrimonios(id_patrimonio),
  id_usuario BIGINT REFERENCES usuarios(id_usuario),
  id_tipo_movimentacao SMALLINT REFERENCES tipos_movimentacao(id_tipo_movimentacao),
  tipo_movimentacao VARCHAR(20) CHECK (tipo_movimentacao IS NULL OR tipo_movimentacao IN ('entrada', 'saida', 'transferencia', 'manutencao', 'baixa')),
  data_mov TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  data_movimentacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  id_origem INTEGER REFERENCES setores_locais(id_setor_local),
  id_destino INTEGER REFERENCES setores_locais(id_setor_local),
  origem VARCHAR(255),
  destino VARCHAR(255),
  event_uuid CHAR(36) UNIQUE,
  observacoes TEXT,
  responsavel VARCHAR(255)
);

CREATE INDEX IF NOT EXISTS idx_movimentacoes_patrimonio_data ON movimentacoes(id_patrimonio, data_mov);

CREATE TABLE IF NOT EXISTS manutencoes (
  id_manutencao BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_patrimonio BIGINT REFERENCES patrimonios(id_patrimonio),
  data_inicio DATE NOT NULL,
  data_fim DATE,
  id_tipo_manutencao SMALLINT REFERENCES tipos_manutencao(id_tipo_manutencao),
  tipo_manutencao VARCHAR(20) CHECK (tipo_manutencao IS NULL OR tipo_manutencao IN ('preventiva', 'corretiva', 'preditiva')),
  id_status_manutencao SMALLINT REFERENCES status_manutencao(id_status_manutencao),
  status VARCHAR(20) NOT NULL DEFAULT 'pendente' CHECK (status IN ('pendente', 'em_andamento', 'concluida', 'cancelada')),
  custo NUMERIC(12,2) CHECK (custo IS NULL OR custo >= 0),
  descricao TEXT,
  responsavel VARCHAR(255),
  empresa VARCHAR(255),
  criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (data_fim IS NULL OR data_fim >= data_inicio)
);

CREATE INDEX IF NOT EXISTS idx_manutencoes_status_inicio ON manutencoes(id_status_manutencao, data_inicio);

CREATE TABLE IF NOT EXISTS depreciacoes (
  id_depreciacao BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_patrimonio BIGINT REFERENCES patrimonios(id_patrimonio),
  data_ref DATE,
  data_depreciacao DATE,
  valor_depreciado NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (valor_depreciado >= 0),
  valor_resultante NUMERIC(12,2) CHECK (valor_resultante IS NULL OR valor_resultante >= 0),
  valor_atual NUMERIC(12,2),
  metodo VARCHAR(50),
  metodo_depreciacao VARCHAR(255),
  criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_depreciacoes_patrimonio_data ON depreciacoes(id_patrimonio, data_ref);

CREATE TABLE IF NOT EXISTS baixas (
  id_baixa BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_patrimonio BIGINT REFERENCES patrimonios(id_patrimonio),
  data_baixa DATE NOT NULL,
  motivo VARCHAR(255) NOT NULL,
  valor_residual NUMERIC(12,2) CHECK (valor_residual IS NULL OR valor_residual >= 0),
  documento VARCHAR(255),
  criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_baixas_patrimonio_data ON baixas(id_patrimonio, data_baixa);

CREATE TABLE IF NOT EXISTS anexos (
  id_anexo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_patrimonio BIGINT REFERENCES patrimonios(id_patrimonio),
  nome VARCHAR(255),
  caminho VARCHAR(255),
  mime VARCHAR(100),
  nome_arquivo VARCHAR(255),
  caminho_arquivo VARCHAR(255),
  tipo_arquivo VARCHAR(100),
  tamanho_arquivo BIGINT,
  data_upload TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS anexos_manutencoes (
  id_anexo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_manutencao BIGINT REFERENCES manutencoes(id_manutencao),
  nome_arquivo VARCHAR(255),
  caminho_arquivo VARCHAR(255),
  tipo_arquivo VARCHAR(100),
  tamanho_arquivo BIGINT,
  data_upload TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS anexos_notas_fiscais (
  id_anexo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_nota_fiscal BIGINT REFERENCES notas_fiscais(id_nota_fiscal),
  nome_arquivo VARCHAR(255),
  caminho_arquivo VARCHAR(255),
  tipo_arquivo VARCHAR(100),
  tamanho_arquivo BIGINT,
  data_upload TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS garantias (
  id_garantia BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_patrimonio BIGINT REFERENCES patrimonios(id_patrimonio),
  data_inicio DATE NOT NULL,
  data_fim DATE,
  termos TEXT,
  documento VARCHAR(255),
  criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (data_fim IS NULL OR data_fim >= data_inicio)
);

CREATE TABLE IF NOT EXISTS auditorias (
  id_auditoria BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario BIGINT REFERENCES usuarios(id_usuario),
  data_evento TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  data_auditoria TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  acao VARCHAR(255) NOT NULL,
  tabela_afetada VARCHAR(255),
  id_registro_afetado BIGINT,
  detalhes_antigos JSONB,
  detalhes_novos JSONB,
  detalhes TEXT
);

INSERT INTO roles (codigo, descricao) VALUES
  ('master', 'Master'),
  ('admin', 'Administrador'),
  ('user', 'Usuario')
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO status_patrimonio (codigo, descricao) VALUES
  ('ativo', 'Ativo'),
  ('baixado', 'Baixado'),
  ('em_manutencao', 'Em manutencao'),
  ('desaparecido', 'Desaparecido')
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO tipos_movimentacao (codigo, descricao) VALUES
  ('entrada', 'Entrada'),
  ('saida', 'Saida'),
  ('transferencia', 'Transferencia'),
  ('manutencao', 'Manutencao'),
  ('baixa', 'Baixa')
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO status_manutencao (codigo, descricao) VALUES
  ('pendente', 'Pendente'),
  ('em_andamento', 'Em andamento'),
  ('concluida', 'Concluida'),
  ('cancelada', 'Cancelada')
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO tipos_manutencao (codigo, descricao) VALUES
  ('preventiva', 'Preventiva'),
  ('corretiva', 'Corretiva'),
  ('preditiva', 'Preditiva')
ON CONFLICT (codigo) DO NOTHING;
