ALTER TABLE usuarios
  ADD COLUMN IF NOT EXISTS ativo SMALLINT NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE fornecedores
  ADD COLUMN IF NOT EXISTS ativo SMALLINT NOT NULL DEFAULT 1;

ALTER TABLE auditorias
  ADD COLUMN IF NOT EXISTS data_auditoria TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS detalhes TEXT;
